#!/usr/bin/env python
# Copyright (c) Nordic Semiconductor ASA. All Rights Reserved.
#
# The information contained herein is confidential property of Nordic Semiconductor ASA.
# The use, copying, transfer or disclosure of such information is prohibited except by
# express written agreement with Nordic Semiconductor ASA.


# -> need CI pipeline stuff, that will be the "internal" things, python script here will only be generic.
# Recommenation: own pipeline.
## This is best as a NCS nightly test, add pipeline there.
## CI-plan (CI-part) best to place in Dragoon.
#--------------------------------------------------------------------------------------------------#

### Step GROOVY:
# see ci_utils.groovy, we want to add there our own KPI pipeline
# dragoon/verification/conf/ci/vars/ci_utils.groovy:1069
    # -> "ptsTestStep" is PTS pipeline
# dragoon/verification/conf/ci/vars/ci_utils.groovy:1178
    # -> "${pts_scripts_path}/tests.py" is where it's specified what PTS tests run. Need something similar to trigger KPI tests run.
# dragoon/verification/conf/ci/vars/ci_utils.groovy:1200
    # -> While the token is obstructed, it can get retrieved with "INFLUXDB_TOKEN", and then just printed or given to whatever needs it.
# dragoon/verification/conf/ci/vars/ci_utils.groovy:1202
    # -> Need out own bucket, not "paladin_pts", TODO: ask Buran to get one.
# dragoon/verification/conf/ci/vars/ci_utils.groovy:1207
    # -> Either modify "influxdb_injector.py" to be more generic, not just for PTS, or make own.
    # -> it should be a rather generic injector script
#--------------------------------------------------------------------------------------------------#

### Step JENKINSFILE
# dragoon/verification/conf/ci/test_ble_pts.jenkinsfile
    # -> This mostly be copied for the KPI tests
# dragoon/verification/conf/ci/test_ble_pts.jenkinsfile:106
    # -> Instead of "ptsTestStep", call ci_utils.kpiTestXX
#--------------------------------------------------------------------------------------------------#

### Step INFLUX_PY:
# -> Have one script that pushes to influxDB for NCS(sdk-nrf), OR modify the PTS dragoon one (influxdb_injector.py) to generalize it to use it.
#--------------------------------------------------------------------------------------------------#

### Step TEST_RESULTS:
# Unsure yet how exactly to provide them. Need to check other tests.
#--------------------------------------------------------------------------------------------------#

### Step REMOVE_TEST_DATA_FROM_DATABASE:
# see this shell script:
# # # export TOKEN=""
# # # export BUCKET=""
# # # curl --request POST "https://ci-health-influxdb.nordicsemi.no/api/v2/delete?org=my-org&bucket=${BUCKET}" \
# # #   --header 'Authorization: Token ${TOKEN}' \
# # #   --header 'Content-Type: application/json' \
# # #   --data '{
# # #     "start": "2000-03-01T00:00:00Z",
# # #     "stop": "2050-11-14T00:00:00Z"
# # #   }'

# replace bucket with KPI bucket to delete test data. Get the token from ci_utils.groovy.
#--------------------------------------------------------------------------------------------------#

## Theo's influxDB injector (dragoon/verification/tests/ble_conf/new_pts/influxdb_injector.py) is using an XML file generated by the PTS test(s). But there is also a nice way in python to push json file (test result data) into influxDB. '
# Dragoon did it in a bit roundabout way, see dragoon/verification/conf/ci/vars/influxdb_summary_injector.py
